// <auto-generated />
using System;
using System.Collections.Generic;
using ControleAtivos.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAtivos.Persistence.Migrations
{
    [DbContext(typeof(ControleAtivosDbContext))]
    [Migration("20260818201100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("controle_ativos")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommended_action");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("TenantId", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_open_deduplication")
                        .HasFilter("status IN ('Aberto', 'EmAnalise')");

                    b.HasIndex("TenantId", "DueDate")
                        .HasDatabaseName("ix_alerts_tenant_id_due_date");

                    b.HasIndex("TenantId", "OrganizationalUnitId", "Status")
                        .HasDatabaseName("ix_alerts_tenant_id_organizational_unit_id_status");

                    b.HasIndex("TenantId", "Status", "Priority")
                        .HasDatabaseName("ix_alerts_tenant_id_status_priority");

                    b.ToTable("alerts", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_subject");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("job_title");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid?>("PrimaryOrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_organizational_unit_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("PrimaryOrganizationalUnitId")
                        .HasDatabaseName("ix_users_primary_organizational_unit_id");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.HasIndex("TenantId", "ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_tenant_id_external_subject");

                    b.ToTable("users", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("billing_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FinancialResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_responsible_user_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<DateOnly?>("LastAdjustmentDate")
                        .HasColumnType("date")
                        .HasColumnName("last_adjustment_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextAdjustmentDate")
                        .HasColumnType("date")
                        .HasColumnName("next_adjustment_date");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date")
                        .HasColumnName("renewal_date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid?>("TechnicalResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("technical_responsible_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MonthlyAmount", "ControleAtivos.Domain.Entities.Asset.MonthlyAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("monthly_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_assets_contract_id");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_assets_cost_center_id");

                    b.HasIndex("FinancialResponsibleUserId")
                        .HasDatabaseName("ix_assets_financial_responsible_user_id");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_assets_organizational_unit_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_assets_supplier_id");

                    b.HasIndex("TechnicalResponsibleUserId")
                        .HasDatabaseName("ix_assets_technical_responsible_user_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_tenant_id_code");

                    b.HasIndex("TenantId", "ContractId")
                        .HasDatabaseName("ix_assets_tenant_id_contract_id");

                    b.HasIndex("TenantId", "OrganizationalUnitId")
                        .HasDatabaseName("ix_assets_tenant_id_organizational_unit_id");

                    b.HasIndex("TenantId", "RenewalDate")
                        .HasDatabaseName("ix_assets_tenant_id_renewal_date");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_assets_tenant_id_status");

                    b.HasIndex("TenantId", "Kind", "Status")
                        .HasDatabaseName("ix_assets_tenant_id_kind_status");

                    b.ToTable("assets", "controle_ativos");

                    b.HasDiscriminator<string>("Kind");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("action");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(200)
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_display_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_tenant_id_entity_type_entity_id");

                    b.HasIndex("TenantId", "UserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_tenant_id_user_id_occurred_at");

                    b.ToTable("audit_logs", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentIndex")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("adjustment_index");

                    b.Property<string>("AdjustmentPeriodicity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("adjustment_periodicity");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("InternalResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("internal_responsible_user_id");

                    b.Property<DateOnly?>("LastAdjustmentDate")
                        .HasColumnType("date")
                        .HasColumnName("last_adjustment_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextAdjustmentDate")
                        .HasColumnType("date")
                        .HasColumnName("next_adjustment_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("number");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MonthlyAmount", "ControleAtivos.Domain.Entities.Contract.MonthlyAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("monthly_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("InternalResponsibleUserId")
                        .HasDatabaseName("ix_contracts_internal_responsible_user_id");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_contracts_organizational_unit_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_contracts_supplier_id");

                    b.HasIndex("TenantId", "EndDate")
                        .HasDatabaseName("ix_contracts_tenant_id_end_date");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_tenant_id_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_contracts_tenant_id_status");

                    b.HasIndex("TenantId", "SupplierId")
                        .HasDatabaseName("ix_contracts_tenant_id_supplier_id");

                    b.ToTable("contracts", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.CostCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_cost_centers");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_cost_centers_organizational_unit_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_cost_centers_tenant_id_code");

                    b.ToTable("cost_centers", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.CostEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateOnly>("CompetenceMonth")
                        .HasColumnType("date")
                        .HasColumnName("competence_month");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<Guid?>("CostCenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cost_center_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "ControleAtivos.Domain.Entities.CostEntry.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cost_entries");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_cost_entries_asset_id");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_cost_entries_contract_id");

                    b.HasIndex("CostCenterId")
                        .HasDatabaseName("ix_cost_entries_cost_center_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_cost_entries_supplier_id");

                    b.HasIndex("TenantId", "CompetenceMonth")
                        .HasDatabaseName("ix_cost_entries_tenant_id_competence_month");

                    b.HasIndex("TenantId", "AssetId", "CompetenceMonth")
                        .HasDatabaseName("ix_cost_entries_tenant_id_asset_id_competence_month");

                    b.HasIndex("TenantId", "OrganizationalUnitId", "CompetenceMonth")
                        .HasDatabaseName("ix_cost_entries_tenant_id_organizational_unit_id_competence_mo~");

                    b.ToTable("cost_entries", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("ix_documents_tenant_id_sha256");

                    b.HasIndex("TenantId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_documents_tenant_id_entity_type_entity_id");

                    b.ToTable("documents", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.ManagementAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IncludesDescendants")
                        .HasColumnType("boolean")
                        .HasColumnName("includes_descendants");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_management_assignments");

                    b.HasIndex("OrganizationalUnitId")
                        .HasDatabaseName("ix_management_assignments_organizational_unit_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_management_assignments_user_id");

                    b.HasIndex("TenantId", "OrganizationalUnitId")
                        .HasDatabaseName("ix_management_assignments_tenant_id_organizational_unit_id");

                    b.HasIndex("TenantId", "UserId", "EndDate")
                        .HasDatabaseName("ix_management_assignments_tenant_id_user_id_end_date");

                    b.HasIndex("TenantId", "UserId", "OrganizationalUnitId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_management_assignments_active_unique")
                        .HasFilter("end_date IS NULL");

                    b.ToTable("management_assignments", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_organizational_units");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_organizational_units_parent_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organizational_units_tenant_id_code");

                    b.HasIndex("TenantId", "ParentId")
                        .HasDatabaseName("ix_organizational_units_tenant_id_parent_id");

                    b.HasIndex("TenantId", "Path")
                        .HasDatabaseName("ix_organizational_units_tenant_path");

                    b.ToTable("organizational_units", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.PriceAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<string>("IndexApplied")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("index_applied");

                    b.Property<Guid>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NewAmount", "ControleAtivos.Domain.Entities.PriceAdjustment.NewAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("new_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("new_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PreviousAmount", "ControleAtivos.Domain.Entities.PriceAdjustment.PreviousAmount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("previous_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("previous_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_price_adjustments");

                    b.HasIndex("TenantId", "EffectiveDate")
                        .HasDatabaseName("ix_price_adjustments_tenant_id_effective_date");

                    b.HasIndex("TenantId", "OrganizationalUnitId")
                        .HasDatabaseName("ix_price_adjustments_tenant_id_organizational_unit_id");

                    b.HasIndex("TenantId", "TargetType", "TargetId")
                        .HasDatabaseName("ix_price_adjustments_tenant_id_target_type_target_id");

                    b.ToTable("price_adjustments", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("document_number");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("MainContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("main_contact_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("SlaDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("sla_description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("TenantId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_tenant_id_document_number")
                        .HasFilter("document_number IS NOT NULL");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_suppliers_tenant_id_name");

                    b.ToTable("suppliers", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("event_type");

                    b.Property<decimal?>("NewAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("new_amount");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OrganizationalUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizational_unit_id");

                    b.Property<decimal?>("PreviousAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("previous_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_display_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_timeline_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_timeline_events_correlation_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_timeline_events_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "EventType", "OccurredAt")
                        .HasDatabaseName("ix_timeline_events_tenant_id_event_type_occurred_at");

                    b.HasIndex("TenantId", "OrganizationalUnitId", "OccurredAt")
                        .HasDatabaseName("ix_timeline_events_tenant_id_organizational_unit_id_occurred_at");

                    b.HasIndex("TenantId", "EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_timeline_events_entity_occurred");

                    b.ToTable("timeline_events", "controle_ativos");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.LicenseAsset", b =>
                {
                    b.HasBaseType("ControleAtivos.Domain.Entities.Asset");

                    b.Property<int>("ContractedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("contracted_quantity");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Plan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("plan");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product");

                    b.Property<int>("UsedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("used_quantity");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "ControleAtivos.Domain.Entities.LicenseAsset.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("unit_price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");
                        });

                    b.ToTable("assets", "controle_ativos");

                    b.HasDiscriminator().HasValue("License");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.ServerAsset", b =>
                {
                    b.HasBaseType("ControleAtivos.Domain.Entities.Asset");

                    b.Property<string>("BackupPolicy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("backup_policy");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_cores");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("environment");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("hostname");

                    b.Property<DateTimeOffset?>("LastBackupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_backup_at");

                    b.Property<string>("MaintenanceWindow")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("maintenance_window");

                    b.Property<int?>("MemoryGb")
                        .HasColumnType("integer")
                        .HasColumnName("memory_gb");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("operating_system");

                    b.Property<string>("OperatingSystemVersion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("operating_system_version");

                    b.Property<string>("PrimaryIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("primary_ip");

                    b.Property<string>("Provider")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider");

                    b.Property<string>("RegionOrDatacenter")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("region_or_datacenter");

                    b.Property<string>("ServerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("server_type");

                    b.Property<string>("Sla")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("sla");

                    b.Property<int?>("StorageGb")
                        .HasColumnType("integer")
                        .HasColumnName("storage_gb");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BackupMonthlyCost", "ControleAtivos.Domain.Entities.ServerAsset.BackupMonthlyCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("backup_monthly_cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("backup_cost_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "InfrastructureMonthlyCost", "ControleAtivos.Domain.Entities.ServerAsset.InfrastructureMonthlyCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("infrastructure_monthly_cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("infrastructure_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LicenseMonthlyCost", "ControleAtivos.Domain.Entities.ServerAsset.LicenseMonthlyCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("license_monthly_cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("license_cost_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SupportMonthlyCost", "ControleAtivos.Domain.Entities.ServerAsset.SupportMonthlyCost#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("support_monthly_cost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("support_cost_currency");
                        });

                    b.ToTable("assets", "controle_ativos");

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "PrimaryOrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("PrimaryOrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_organizational_units_primary_organizational_unit_id");

                    b.Navigation("PrimaryOrganizationalUnit");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.Contract", "Contract")
                        .WithMany("Assets")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_contracts_contract_id");

                    b.HasOne("ControleAtivos.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_cost_centers_cost_center_id");

                    b.HasOne("ControleAtivos.Domain.Entities.AppUser", "FinancialResponsible")
                        .WithMany()
                        .HasForeignKey("FinancialResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_users_financial_responsible_user_id");

                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assets_organizational_units_organizational_unit_id");

                    b.HasOne("ControleAtivos.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_suppliers_supplier_id");

                    b.HasOne("ControleAtivos.Domain.Entities.AppUser", "TechnicalResponsible")
                        .WithMany()
                        .HasForeignKey("TechnicalResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assets_users_technical_responsible_user_id");

                    b.Navigation("Contract");

                    b.Navigation("CostCenter");

                    b.Navigation("FinancialResponsible");

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Supplier");

                    b.Navigation("TechnicalResponsible");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Contract", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.AppUser", "InternalResponsible")
                        .WithMany()
                        .HasForeignKey("InternalResponsibleUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_contracts_users_internal_responsible_user_id");

                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_organizational_units_organizational_unit_id");

                    b.HasOne("ControleAtivos.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Contracts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_suppliers_supplier_id");

                    b.Navigation("InternalResponsible");

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.CostCenter", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany()
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cost_centers_organizational_units_organizational_unit_id");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.CostEntry", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.Asset", "Asset")
                        .WithMany("CostEntries")
                        .HasForeignKey("AssetId")
                        .HasConstraintName("fk_cost_entries_assets_asset_id");

                    b.HasOne("ControleAtivos.Domain.Entities.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cost_entries_contracts_contract_id");

                    b.HasOne("ControleAtivos.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cost_entries_cost_centers_cost_center_id");

                    b.HasOne("ControleAtivos.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cost_entries_suppliers_supplier_id");

                    b.Navigation("Asset");

                    b.Navigation("Contract");

                    b.Navigation("CostCenter");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.ManagementAssignment", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("ManagementAssignments")
                        .HasForeignKey("OrganizationalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_assignments_organizational_units_organizational_~");

                    b.HasOne("ControleAtivos.Domain.Entities.AppUser", "User")
                        .WithMany("ManagementAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_management_assignments_users_user_id");

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.HasOne("ControleAtivos.Domain.Entities.OrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_organizational_units_organizational_units_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("ManagementAssignments");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Asset", b =>
                {
                    b.Navigation("CostEntries");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Contract", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.OrganizationalUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ManagementAssignments");
                });

            modelBuilder.Entity("ControleAtivos.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
