import type {
  Alert,
  ContractExpirationReport,
  ContractListItem,
  CostEvolutionReport,
  CostSummary,
  DashboardSummary,
  LicenseListItem,
  LicenseUtilizationReport,
  ManagementAssignment,
  OrganizationalUnitTree,
  PagedResult,
  PriceAdjustmentListItem,
  ServerListItem,
  SupplierListItem,
  TimelineEvent,
} from '../models';

const now = new Date();
const iso = (days = 0) => new Date(now.getTime() + days * 86_400_000).toISOString();
const date = (days = 0) => iso(days).slice(0, 10);

export const timelineEvents: readonly TimelineEvent[] = [
  {
    id: 'evt-1',
    entityType: 'License',
    entityId: 'lic-1',
    eventType: 'ReajusteAplicado',
    title: 'Reajuste Microsoft 365 aplicado',
    description:
      'Valor mensal alterado de R$ 11.040,00 para R$ 12.600,00. Impacto anual de R$ 18.720,00.',
    occurredAt: iso(-4),
    userId: 'usr-1',
    userDisplayName: 'Ana Souza',
    previousAmount: 11040,
    newAmount: 12600,
    financialImpact: 1560,
    organizationalUnitId: 'uo-1',
    organizationalUnitName: 'Transformação Digital',
    correlationId: 'corr-1',
  },
  {
    id: 'evt-2',
    entityType: 'Server',
    entityId: 'srv-1',
    eventType: 'AlteracaoValor',
    title: 'Servidor APP-PRD-01 redimensionado',
    description:
      'Memória alterada de 16 GB para 32 GB. Custo mensal subiu de R$ 850,00 para R$ 1.120,00.',
    occurredAt: iso(-9),
    userId: 'usr-2',
    userDisplayName: 'Carlos Lima',
    previousAmount: 850,
    newAmount: 1120,
    financialImpact: 270,
    organizationalUnitId: 'uo-2',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    correlationId: 'corr-2',
  },
  {
    id: 'evt-3',
    entityType: 'Contract',
    entityId: 'ct-1',
    eventType: 'Renovacao',
    title: 'Contrato Microsoft CSP em renovação',
    description: 'Renovação em análise com vencimento em 25 dias.',
    occurredAt: iso(-12),
    userId: 'usr-1',
    userDisplayName: 'Ana Souza',
    previousAmount: null,
    newAmount: null,
    financialImpact: null,
    organizationalUnitId: 'uo-1',
    organizationalUnitName: 'Transformação Digital',
    correlationId: 'corr-3',
  },
];

export const licenses: readonly LicenseListItem[] = [
  {
    id: 'lic-1',
    name: 'Microsoft 365 Business Premium',
    code: 'LIC-M365-BP',
    manufacturer: 'Microsoft',
    product: 'Microsoft 365 Business Premium',
    plan: null,
    status: 'Ativo',
    billingType: 'Mensal',
    contractedQuantity: 120,
    usedQuantity: 104,
    availableQuantity: 16,
    utilizationRate: 86.67,
    unitPrice: 105,
    monthlyAmount: 12600,
    annualAmount: 151200,
    currency: 'BRL',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Transformação Digital',
    renewalDate: date(25),
    lastAdjustmentDate: date(-60),
    nextAdjustmentDate: date(305),
  },
  {
    id: 'lic-2',
    name: 'Microsoft 365 E3',
    code: 'LIC-M365-E3',
    manufacturer: 'Microsoft',
    product: 'Microsoft 365 E3',
    plan: null,
    status: 'Ativo',
    billingType: 'Mensal',
    contractedQuantity: 35,
    usedQuantity: 32,
    availableQuantity: 3,
    utilizationRate: 91.43,
    unitPrice: 185,
    monthlyAmount: 6475,
    annualAmount: 77700,
    currency: 'BRL',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Desenvolvimento de Sistemas',
    renewalDate: date(25),
    lastAdjustmentDate: null,
    nextAdjustmentDate: date(305),
  },
  {
    id: 'lic-3',
    name: 'Power BI Pro',
    code: 'LIC-PBI-PRO',
    manufacturer: 'Microsoft',
    product: 'Power BI Pro',
    plan: null,
    status: 'Ativo',
    billingType: 'Mensal',
    contractedQuantity: 45,
    usedQuantity: 18,
    availableQuantity: 27,
    utilizationRate: 40,
    unitPrice: 59.9,
    monthlyAmount: 2695.5,
    annualAmount: 32346,
    currency: 'BRL',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Engenharia de Dados',
    renewalDate: date(40),
    lastAdjustmentDate: null,
    nextAdjustmentDate: date(320),
  },
  {
    id: 'lic-4',
    name: 'Exchange Online Plan 2',
    code: 'LIC-EXO-P2',
    manufacturer: 'Microsoft',
    product: 'Exchange Online Plan 2',
    plan: null,
    status: 'Ativo',
    billingType: 'Mensal',
    contractedQuantity: 80,
    usedQuantity: 76,
    availableQuantity: 4,
    utilizationRate: 95,
    unitPrice: 48,
    monthlyAmount: 3840,
    annualAmount: 46080,
    currency: 'BRL',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Transformação Digital',
    renewalDate: date(25),
    lastAdjustmentDate: null,
    nextAdjustmentDate: date(300),
  },
  {
    id: 'lic-5',
    name: 'Project Plan 3',
    code: 'LIC-PRJ-P3',
    manufacturer: 'Microsoft',
    product: 'Project Plan 3',
    plan: null,
    status: 'Ativo',
    billingType: 'Mensal',
    contractedQuantity: 12,
    usedQuantity: 9,
    availableQuantity: 3,
    utilizationRate: 75,
    unitPrice: 165,
    monthlyAmount: 1980,
    annualAmount: 23760,
    currency: 'BRL',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Desenvolvimento de Sistemas',
    renewalDate: date(60),
    lastAdjustmentDate: null,
    nextAdjustmentDate: date(330),
  },
];

export const servers: readonly ServerListItem[] = [
  {
    id: 'srv-1',
    name: 'APP-PRD-01',
    code: 'SRV-APP-PRD-01',
    hostname: 'app-prd-01.contoso.local',
    serverType: 'Virtual',
    environment: 'Producao',
    status: 'Ativo',
    operatingSystem: 'Ubuntu Server 22.04',
    provider: 'Azure Cloud Services',
    cpuCores: 8,
    memoryGb: 32,
    storageGb: 500,
    monthlyAmount: 1411.2,
    annualAmount: 16934.4,
    currency: 'BRL',
    technicalResponsibleName: 'Carlos Lima',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    lastBackupAt: iso(-1),
    hasResponsible: true,
  },
  {
    id: 'srv-2',
    name: 'DB-PRD-01',
    code: 'SRV-DB-PRD-01',
    hostname: 'db-prd-01.contoso.local',
    serverType: 'BancoDados',
    environment: 'Producao',
    status: 'Ativo',
    operatingSystem: 'Windows Server 2022',
    provider: 'Azure Cloud Services',
    cpuCores: 16,
    memoryGb: 64,
    storageGb: 2000,
    monthlyAmount: 4851,
    annualAmount: 58212,
    currency: 'BRL',
    technicalResponsibleName: 'Carlos Lima',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    lastBackupAt: iso(-1),
    hasResponsible: true,
  },
  {
    id: 'srv-3',
    name: 'AD-01',
    code: 'SRV-AD-01',
    hostname: 'ad-01.contoso.local',
    serverType: 'Virtual',
    environment: 'Producao',
    status: 'Ativo',
    operatingSystem: 'Windows Server 2019',
    provider: 'Azure Cloud Services',
    cpuCores: 4,
    memoryGb: 16,
    storageGb: 300,
    monthlyAmount: 1159.2,
    annualAmount: 13910.4,
    currency: 'BRL',
    technicalResponsibleName: 'Carlos Lima',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    lastBackupAt: iso(-9),
    hasResponsible: true,
  },
  {
    id: 'srv-4',
    name: 'HML-WEB-01',
    code: 'SRV-HML-WEB-01',
    hostname: 'hml-web-01.contoso.local',
    serverType: 'Aplicacao',
    environment: 'Homologacao',
    status: 'Ativo',
    operatingSystem: 'Ubuntu Server 22.04',
    provider: 'Azure Cloud Services',
    cpuCores: 4,
    memoryGb: 8,
    storageGb: 200,
    monthlyAmount: 516.6,
    annualAmount: 6199.2,
    currency: 'BRL',
    technicalResponsibleName: 'Marina Rocha',
    organizationalUnitName: 'Desenvolvimento de Sistemas',
    lastBackupAt: null,
    hasResponsible: true,
  },
  {
    id: 'srv-5',
    name: 'ROBO-SIM-01',
    code: 'SRV-ROBO-SIM-01',
    hostname: 'robo-sim-01.contoso.local',
    serverType: 'Fisico',
    environment: 'Desenvolvimento',
    status: 'PendenteRevisao',
    operatingSystem: 'Windows Server 2022',
    provider: 'Dell Technologies',
    cpuCores: 32,
    memoryGb: 128,
    storageGb: 4000,
    monthlyAmount: 2898,
    annualAmount: 34776,
    currency: 'BRL',
    technicalResponsibleName: null,
    organizationalUnitName: 'Robótica Industrial',
    lastBackupAt: null,
    hasResponsible: false,
  },
];

export const contracts: readonly ContractListItem[] = [
  {
    id: 'ct-1',
    number: 'CT-2025-001',
    name: 'Licenciamento Microsoft CSP',
    category: 'Licenciamento',
    status: 'Ativo',
    supplierId: 'sup-1',
    supplierName: 'Microsoft CSP Brasil',
    organizationalUnitName: 'Transformação Digital',
    monthlyAmount: 24500,
    annualAmount: 294000,
    currency: 'BRL',
    startDate: date(-300),
    endDate: date(25),
    daysUntilExpiration: 25,
    adjustmentIndex: 'NegociacaoManual',
    nextAdjustmentDate: date(305),
    linkedAssetCount: 7,
    internalResponsibleName: 'Ana Souza',
  },
  {
    id: 'ct-2',
    number: 'CT-2025-002',
    name: 'Infraestrutura Azure',
    category: 'Cloud',
    status: 'Ativo',
    supplierId: 'sup-2',
    supplierName: 'Azure Cloud Services',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    monthlyAmount: 18200,
    annualAmount: 218400,
    currency: 'BRL',
    startDate: date(-240),
    endDate: date(75),
    daysUntilExpiration: 75,
    adjustmentIndex: 'Dolar',
    nextAdjustmentDate: date(180),
    linkedAssetCount: 4,
    internalResponsibleName: 'Carlos Lima',
  },
  {
    id: 'ct-3',
    number: 'CT-2025-003',
    name: 'Backup corporativo Veeam',
    category: 'Backup',
    status: 'Ativo',
    supplierId: 'sup-4',
    supplierName: 'Veeam Partner Brasil',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    monthlyAmount: 3400,
    annualAmount: 40800,
    currency: 'BRL',
    startDate: date(-420),
    endDate: date(160),
    daysUntilExpiration: 160,
    adjustmentIndex: 'Ipca',
    nextAdjustmentDate: date(160),
    linkedAssetCount: 1,
    internalResponsibleName: 'Carlos Lima',
  },
];

export const suppliers: readonly SupplierListItem[] = [
  {
    id: 'sup-1',
    name: 'Microsoft CSP Brasil',
    documentNumber: '12345678000190',
    category: 'Licenciamento',
    status: 'Ativo',
    mainContactName: 'Atendimento Corporativo',
    email: 'contato@microsoft.com.br',
    phone: '(71) 3000-0000',
    activeContracts: 1,
    linkedAssets: 7,
    monthlyAmount: 29690.5,
    annualAmount: 356286,
    currency: 'BRL',
  },
  {
    id: 'sup-2',
    name: 'Azure Cloud Services',
    documentNumber: '12345678000271',
    category: 'Cloud',
    status: 'Ativo',
    mainContactName: 'Atendimento Corporativo',
    email: 'contato@azure.com.br',
    phone: '(71) 3000-0000',
    activeContracts: 1,
    linkedAssets: 4,
    monthlyAmount: 7938,
    annualAmount: 95256,
    currency: 'BRL',
  },
  {
    id: 'sup-3',
    name: 'Dell Technologies',
    documentNumber: '72381189000110',
    category: 'Infraestrutura',
    status: 'Ativo',
    mainContactName: 'Atendimento Corporativo',
    email: 'contato@dell.com.br',
    phone: '(71) 3000-0000',
    activeContracts: 1,
    linkedAssets: 1,
    monthlyAmount: 2898,
    annualAmount: 34776,
    currency: 'BRL',
  },
];

export const adjustments: readonly PriceAdjustmentListItem[] = [
  {
    id: 'adj-1',
    targetType: 'Asset',
    targetId: 'lic-1',
    targetName: 'Microsoft 365 Business Premium',
    previousAmount: 11040,
    newAmount: 12600,
    absoluteDifference: 1560,
    percentageDifference: 14.13,
    annualImpact: 18720,
    currency: 'BRL',
    effectiveDate: date(-60),
    reason: 'Reajuste anual do fornecedor após negociação comercial',
    indexApplied: 'NegociacaoManual',
    createdByName: 'Ana Souza',
    approvedByName: 'Paulo Dias',
    organizationalUnitName: 'Transformação Digital',
    exceedsThreshold: true,
  },
  {
    id: 'adj-2',
    targetType: 'Asset',
    targetId: 'srv-1',
    targetName: 'APP-PRD-01',
    previousAmount: 850,
    newAmount: 1120,
    absoluteDifference: 270,
    percentageDifference: 31.76,
    annualImpact: 3240,
    currency: 'BRL',
    effectiveDate: date(-90),
    reason: 'Upgrade de memória para suportar aumento de carga',
    indexApplied: 'NegociacaoManual',
    createdByName: 'Carlos Lima',
    approvedByName: 'Ana Souza',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    exceedsThreshold: true,
  },
];

export const alerts: readonly Alert[] = [
  {
    id: 'al-1',
    type: 'ContratoVencendo',
    priority: 'Alta',
    status: 'Aberto',
    entityType: 'Contract',
    entityId: 'ct-1',
    title: 'Contrato CT-2025-001 vence em 25 dias',
    description: 'Contrato Microsoft CSP precisa de decisão de renovação.',
    recommendedAction: 'Avaliar renovação e quantidade de licenças antes do vencimento.',
    dueDate: date(25),
    assignedToUserId: null,
    assignedToName: null,
    organizationalUnitName: 'Transformação Digital',
    createdAt: iso(-1),
    resolvedAt: null,
    resolutionNotes: null,
  },
  {
    id: 'al-2',
    type: 'LicencaBaixaUtilizacao',
    priority: 'Media',
    status: 'Aberto',
    entityType: 'License',
    entityId: 'lic-3',
    title: 'Power BI Pro com 40% de utilização',
    description: 'Há 27 licenças potencialmente ociosas.',
    recommendedAction: 'Revisar alocação antes da renovação.',
    dueDate: null,
    assignedToUserId: null,
    assignedToName: null,
    organizationalUnitName: 'Engenharia de Dados',
    createdAt: iso(-2),
    resolvedAt: null,
    resolutionNotes: null,
  },
  {
    id: 'al-3',
    type: 'ServidorSemBackupRecente',
    priority: 'Critica',
    status: 'EmAnalise',
    entityType: 'Server',
    entityId: 'srv-3',
    title: 'AD-01 sem backup recente',
    description: 'Último backup registrado há mais de 3 dias.',
    recommendedAction: 'Verificar rotina de backup imediatamente.',
    dueDate: null,
    assignedToUserId: 'usr-2',
    assignedToName: 'Carlos Lima',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    createdAt: iso(-1),
    resolvedAt: null,
    resolutionNotes: null,
  },
];

export const costSummary: CostSummary = {
  currentMonthlyCost: 51542.5,
  projectedAnnualCost: 618510,
  currency: 'BRL',
  adjustedThisMonth: 0,
  accumulatedMonthlyImpact: 1830,
  accumulatedAnnualImpact: 21960,
  highestPercentageIncrease: 31.76,
  highestAbsoluteIncrease: 1560,
  assetsWithoutAdjustmentOver12Months: 5,
  adjustmentsInPeriod: 2,
  byCategory: [
    { label: 'License', id: null, monthlyAmount: 29690.5, annualAmount: 356286, itemCount: 5 },
    { label: 'Server', id: null, monthlyAmount: 21852, annualAmount: 262224, itemCount: 5 },
  ],
  bySupplier: [
    {
      label: 'Microsoft CSP Brasil',
      id: 'sup-1',
      monthlyAmount: 29690.5,
      annualAmount: 356286,
      itemCount: 7,
    },
    {
      label: 'Azure Cloud Services',
      id: 'sup-2',
      monthlyAmount: 7938,
      annualAmount: 95256,
      itemCount: 4,
    },
    {
      label: 'Dell Technologies',
      id: 'sup-3',
      monthlyAmount: 2898,
      annualAmount: 34776,
      itemCount: 1,
    },
  ],
  byOrganizationalUnit: [
    {
      label: 'Transformação Digital',
      id: 'uo-1',
      monthlyAmount: 19885.5,
      annualAmount: 238626,
      itemCount: 3,
    },
    {
      label: 'Núcleo de Infraestrutura',
      id: 'uo-2',
      monthlyAmount: 15199.4,
      annualAmount: 182392.8,
      itemCount: 4,
    },
    {
      label: 'Desenvolvimento de Sistemas',
      id: 'uo-3',
      monthlyAmount: 8971.6,
      annualAmount: 107659.2,
      itemCount: 3,
    },
  ],
};

export const dashboardSummary: DashboardSummary = {
  currentMonthlyCost: costSummary.currentMonthlyCost,
  projectedAnnualCost: costSummary.projectedAnnualCost,
  currency: 'BRL',
  activeLicenses: 7,
  activeServers: 5,
  totalContractedLicenses: 311,
  totalUsedLicenses: 249,
  idleLicenses: 2,
  contractsExpiringIn30Days: 1,
  contractsExpiringIn60Days: 1,
  contractsExpiringIn90Days: 2,
  openAlerts: 3,
  criticalAlerts: 1,
  costsByCategory: costSummary.byCategory.map((c) => ({
    category: c.label,
    monthlyAmount: c.monthlyAmount,
    annualAmount: c.annualAmount,
  })),
  topCosts: [
    {
      assetId: 'lic-1',
      name: 'Microsoft 365 Business Premium',
      kind: 'License',
      monthlyAmount: 12600,
      annualAmount: 151200,
    },
    {
      assetId: 'srv-2',
      name: 'DB-PRD-01',
      kind: 'Server',
      monthlyAmount: 4851,
      annualAmount: 58212,
    },
    {
      assetId: 'lic-2',
      name: 'Microsoft 365 E3',
      kind: 'License',
      monthlyAmount: 6475,
      annualAmount: 77700,
    },
  ],
  serversByEnvironment: [
    { environment: 'Producao', count: 3, monthlyAmount: 7421.4 },
    { environment: 'Homologacao', count: 1, monthlyAmount: 516.6 },
    { environment: 'Desenvolvimento', count: 1, monthlyAmount: 2898 },
  ],
  latestEvents: timelineEvents,
};

export const orgTree: readonly OrganizationalUnitTree[] = [
  {
    id: 'matriz',
    parentId: null,
    type: 'Matriz',
    name: 'Contoso Holding',
    code: 'CONTOSO',
    path: '/CONTOSO/',
    level: 0,
    isActive: true,
    assetCount: 13,
    monthlyCost: 51542.5,
    children: [
      {
        id: 'neg-1',
        parentId: 'matriz',
        type: 'Negocio',
        name: 'Negócios de Tecnologia',
        code: 'NEG-TEC',
        path: '/CONTOSO/NEG-TEC/',
        level: 1,
        isActive: true,
        assetCount: 12,
        monthlyCost: 48644.5,
        children: [
          {
            id: 'uo-1',
            parentId: 'neg-1',
            type: 'AreaTecnologica',
            name: 'Transformação Digital',
            code: 'AT-DIGITAL',
            path: '/CONTOSO/NEG-TEC/AT-DIGITAL/',
            level: 2,
            isActive: true,
            assetCount: 8,
            monthlyCost: 38800,
            children: [],
          },
          {
            id: 'uo-4',
            parentId: 'neg-1',
            type: 'AreaTecnologica',
            name: 'Manufatura Avançada',
            code: 'AT-MANUF',
            path: '/CONTOSO/NEG-TEC/AT-MANUF/',
            level: 2,
            isActive: true,
            assetCount: 2,
            monthlyCost: 4083,
            children: [],
          },
        ],
      },
    ],
  },
];

export const assignments: readonly ManagementAssignment[] = [
  {
    id: 'asg-1',
    userId: 'usr-1',
    userDisplayName: 'Ana Souza',
    userEmail: 'ana.souza@example.com',
    organizationalUnitId: 'uo-1',
    organizationalUnitName: 'Transformação Digital',
    organizationalUnitPath: '/CONTOSO/NEG-TEC/AT-DIGITAL/',
    organizationalUnitType: 'AreaTecnologica',
    role: 'Gerente',
    startDate: date(-365),
    endDate: null,
    isPrimary: true,
    includesDescendants: true,
    isActive: true,
  },
  {
    id: 'asg-2',
    userId: 'usr-1',
    userDisplayName: 'Ana Souza',
    userEmail: 'ana.souza@example.com',
    organizationalUnitId: 'uo-4',
    organizationalUnitName: 'Manufatura Avançada',
    organizationalUnitPath: '/CONTOSO/NEG-TEC/AT-MANUF/',
    organizationalUnitType: 'AreaTecnologica',
    role: 'Gerente',
    startDate: date(-365),
    endDate: null,
    isPrimary: false,
    includesDescendants: true,
    isActive: true,
  },
  {
    id: 'asg-3',
    userId: 'usr-2',
    userDisplayName: 'Carlos Lima',
    userEmail: 'carlos.lima@example.com',
    organizationalUnitId: 'uo-2',
    organizationalUnitName: 'Núcleo de Infraestrutura',
    organizationalUnitPath: '/CONTOSO/NEG-TEC/AT-DIGITAL/UO-SIST/NS-INFRA/',
    organizationalUnitType: 'NucleoSuporte',
    role: 'Coordenador',
    startDate: date(-300),
    endDate: null,
    isPrimary: true,
    includesDescendants: true,
    isActive: true,
  },
];

export const costEvolution: CostEvolutionReport = {
  currentMonthlyCost: costSummary.currentMonthlyCost,
  projectedAnnualCost: costSummary.projectedAnnualCost,
  currency: 'BRL',
  history: Array.from({ length: 12 }, (_, index) => {
    const month = new Date(now.getFullYear(), now.getMonth() - 11 + index, 1);
    return {
      year: month.getFullYear(),
      month: month.getMonth() + 1,
      label: month.toLocaleDateString('pt-BR', { month: 'short', year: '2-digit' }),
      amount: Math.round((42000 + index * 850 + (index > 8 ? 2500 : 0)) * 100) / 100,
      currency: 'BRL',
    };
  }),
  projection: Array.from({ length: 12 }, (_, index) => {
    const month = new Date(now.getFullYear(), now.getMonth() + 1 + index, 1);
    return {
      year: month.getFullYear(),
      month: month.getMonth() + 1,
      label: month.toLocaleDateString('pt-BR', { month: 'short', year: '2-digit' }),
      amount: costSummary.currentMonthlyCost,
      currency: 'BRL',
    };
  }),
};

export const licenseUtilizationReport: readonly LicenseUtilizationReport[] = licenses
  .filter((license) => license.utilizationRate <= 70)
  .map((license) => ({
    id: license.id,
    name: license.name,
    product: license.product,
    contractedQuantity: license.contractedQuantity,
    usedQuantity: license.usedQuantity,
    availableQuantity: license.availableQuantity,
    utilizationRate: license.utilizationRate,
    monthlyAmount: license.monthlyAmount,
    potentialMonthlySavings: Math.round(license.availableQuantity * license.unitPrice * 100) / 100,
    currency: license.currency,
    organizationalUnitName: license.organizationalUnitName,
  }));

export const contractExpirationReport: readonly ContractExpirationReport[] = contracts.map(
  (contract) => ({
    id: contract.id,
    number: contract.number,
    name: contract.name,
    supplierName: contract.supplierName,
    monthlyAmount: contract.monthlyAmount,
    currency: contract.currency,
    endDate: contract.endDate,
    daysUntilExpiration: contract.daysUntilExpiration,
    organizationalUnitName: contract.organizationalUnitName,
  }),
);

export function page<T>(items: readonly T[], pageNumber = 1, pageSize = 20): PagedResult<T> {
  const start = (pageNumber - 1) * pageSize;
  const sliced = items.slice(start, start + pageSize);
  const totalPages = Math.ceil(items.length / pageSize) || 1;

  return {
    items: sliced,
    page: pageNumber,
    pageSize,
    totalItems: items.length,
    totalPages,
    hasPrevious: pageNumber > 1,
    hasNext: pageNumber < totalPages,
  };
}
